import { LeagueLayout } from "@/components/LeagueLayout";
import { draftPreview, franchises, leagueMeta, matchups, rosterPreview, setupAreas, transactionFeed } from "@/lib/leagueData";
import { cn } from "@/lib/utils";
import { trpc } from "@/lib/trpc";
import { CommissionerPanel } from "@/components/CommissionerPanel";
import { Activity, ArrowRight, BadgeDollarSign, BookOpen, CalendarDays, Check, ChevronRight, ClipboardList, Crown, FileText, Gavel, LayoutDashboard, ListFilter, Newspaper, Plus, Radio, ReceiptText, Scale, Settings2, ShieldCheck, Sparkles, Trophy, Upload, UsersRound, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

export type PageKind = "standings" | "live" | "lineup" | "draft" | "draft-lottery" | "draft-recap" | "rundown" | "news" | "transactions" | "trades" | "free-agents" | "results" | "history" | "playoffs" | "rules" | "nfl-sites" | "rosters" | "money" | "settings" | "player";

const pageMeta: Record<PageKind, { eyebrow: string; title: string; detail: string; icon: React.ElementType }> = {
  standings: { eyebrow: "League table", title: "Standings", detail: "The current competitive picture, driven by CVC-configured records, divisions, and tiebreakers.", icon: Trophy },
  live: { eyebrow: "Game center", title: "Live scoring", detail: "A provider-neutral scoring surface that will connect to the CVC NFL data adapter once a source is selected.", icon: Radio },
  lineup: { eyebrow: "Owner workspace", title: "My lineup", detail: "Set starters, manage your roster, and review matchup projections in one secure owner view.", icon: ClipboardList },
  draft: { eyebrow: "Draft room", title: "Draft hub", detail: "Configuration-ready draft board, pick ownership, protections, and timing controls.", icon: Gavel },
  "draft-lottery": { eyebrow: "Draft room", title: "Draft lottery", detail: "A transparent lottery surface that can be enabled if CVC uses a lottery draft order.", icon: Sparkles },
  "draft-recap": { eyebrow: "Draft room", title: "Draft recap", detail: "Review selections, traded picks, and post-draft outcomes across CVC seasons.", icon: FileText },
  rundown: { eyebrow: "League desk", title: "Commissioner rundown", detail: "A polished landing area for league updates, weekly context, and key deadlines.", icon: Newspaper },
  news: { eyebrow: "Player desk", title: "Player news", detail: "A source-agnostic player news surface with provider attribution ready to be configured.", icon: Activity },
  transactions: { eyebrow: "League ledger", title: "Transactions", detail: "Every addition, drop, waiver award, commissioner correction, and roster move in one audit-friendly feed.", icon: ReceiptText },
  trades: { eyebrow: "Trade desk", title: "Trades", detail: "Review trade proposals, approval state, assets, deadlines, and commissioner decisions.", icon: Scale },
  "free-agents": { eyebrow: "Player pool", title: "Free agents & FAAB", detail: "A configurable claim and bid workflow designed around CVC waiver rules and budget settings.", icon: BadgeDollarSign },
  results: { eyebrow: "Scoreboard", title: "Schedule & results", detail: "League weeks, matchup outcomes, and schedule structure ready for commissioner import.", icon: CalendarDays },
  history: { eyebrow: "Archive", title: "League history", detail: "A permanent home for champions, records, prior seasons, and memorable CVC moments.", icon: BookOpen },
  playoffs: { eyebrow: "Postseason", title: "Playoffs", detail: "A configurable playoff bracket with seeding, matchup, and tiebreaker support.", icon: Crown },
  rules: { eyebrow: "League governance", title: "Rules & policies", detail: "Versioned CVC rules documents will publish directly from commissioner-managed content.", icon: ShieldCheck },
  "nfl-sites": { eyebrow: "Reference desk", title: "NFL sites", detail: "Commissioner-curated reference links, data-source acknowledgements, and league resources.", icon: ListFilter },
  rosters: { eyebrow: "Franchises", title: "Rosters", detail: "Explore every CVC franchise, owner identity, roster build, and weekly status.", icon: UsersRound },
  money: { eyebrow: "League office", title: "League finance", detail: "A private league-ledger view for dues, payouts, balances, and commissioner financial notes.", icon: WalletCards },
  settings: { eyebrow: "Commissioner office", title: "League configuration", detail: "Set up CVC teams, owners, scoring, schedule, rules, and financial settings without code changes.", icon: Settings2 },
  player: { eyebrow: "Player profile", title: "Player detail", detail: "A reusable player profile for current status, scoring, news, game logs, and roster availability.", icon: Activity },
};

function PageHeader({ kind, action }: { kind: PageKind; action?: React.ReactNode }) {
  const meta = pageMeta[kind];
  const Icon = meta.icon;
  return <div className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="cvc-eyebrow"><Icon size={14} /> {meta.eyebrow}</div><h1 className="mt-2 font-display text-5xl uppercase leading-none tracking-[0.04em] text-white sm:text-6xl">{meta.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-cvc-muted">{meta.detail}</p></div>{action}</div>;
}

function Card({ title, children, action, className }: { title?: string; children: React.ReactNode; action?: React.ReactNode; className?: string }) {
  return <section className={cn("cvc-card", className)}>{title ? <div className="cvc-card-title"><span>{title}</span>{action}</div> : null}<div className="cvc-card-stripe" /><div className="cvc-card-body">{children}</div></section>;
}

function StatusPill({ state }: { state: string }) { return <span className={cn("cvc-pill", state.toLowerCase())}>{state}</span>; }

function Standings() {
  const overview = trpc.league.overview.useQuery();
  const liveFranchises = overview.data?.franchises ?? franchises.map(team => ({ id: team.id, name: team.name, division_name: team.division, record: team.record, pointsFor: team.pointsFor, brand_color: team.color }));
  return <div className="grid gap-6 xl:grid-cols-[1.45fr_0.75fr]"><Card title="CVC standings"><div className="overflow-x-auto"><table className="cvc-table"><thead><tr><th>Franchise</th><th>Division</th><th>Record</th><th>PF</th><th>Rank</th></tr></thead><tbody>{liveFranchises.map((team, index) => <tr key={team.id}><td><div className="flex items-center gap-3"><span className="cvc-rank">{index + 1}</span><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: team.brand_color ?? "#30d5c8" }} /><span className="font-semibold">{team.name}</span></div></td><td>{team.division_name ?? "Unassigned"}</td><td className="font-semibold">{team.record}</td><td>{Number(team.pointsFor).toFixed(1)}</td><td><StatusPill state={index < 3 ? "Playoff" : "In hunt"} /></td></tr>)}</tbody></table></div></Card><div className="space-y-6"><Card title="League foundation"><p className="text-sm leading-6 text-slate-600">CVC demonstration records now load from the secured league database. Commissioner setup replaces these records with actual teams, standings rules, and season details.</p><div className="mt-5 grid grid-cols-2 gap-3"><Metric value={String(liveFranchises.length)} label="Configured franchises" /><Metric value="2" label="Placeholder divisions" /><Metric value="Configurable" label="Tiebreakers" /><Metric value={overview.isLoading ? "Syncing" : "Connected"} label="Supabase data" /></div></Card><Card title="Next matchup"><p className="font-display text-2xl uppercase text-cvc-deep">Atlas Aces <span className="text-cvc-accent">vs</span> Metro Monarchs</p><p className="mt-2 text-sm text-slate-500">Week 11 · Schedule subject to CVC commissioner import</p><Link href="/results" className="cvc-text-link mt-5">View schedule <ChevronRight size={15} /></Link></Card></div></div>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-lg bg-cvc-tint px-3 py-3"><div className="font-display text-xl uppercase text-cvc-deep">{value}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">{label}</div></div>; }
function ModuleState({ label }: { label: string }) { return <div className="rounded-lg border border-dashed border-cvc-deep/20 bg-cvc-tint p-6 text-center text-sm text-slate-600">{label}</div>; }

function MatchupBoard({ liveOnly = false }: { liveOnly?: boolean }) {
  const rows = liveOnly ? matchups.filter(item => item.state === "Live" || item.state === "Upcoming") : matchups;
  return <div className="grid gap-4 md:grid-cols-2">{rows.map((matchup, index) => <div className="cvc-matchup" key={`${matchup.week}-${index}`}><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.13em] text-slate-500"><span>Week {matchup.week}</span><StatusPill state={matchup.state} /></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div><p className="font-display text-xl uppercase text-cvc-deep">{matchup.away}</p><p className="mt-1 text-xs text-slate-500">Away</p></div><strong className="font-display text-3xl text-cvc-deep">{matchup.awayScore || "–"}<span className="mx-1 text-cvc-accent">:</span>{matchup.homeScore || "–"}</strong><div className="text-right"><p className="font-display text-xl uppercase text-cvc-deep">{matchup.home}</p><p className="mt-1 text-xs text-slate-500">Home</p></div></div></div>)}</div>;
}

function LiveScoring() { return <div className="space-y-6"><Card title="Week 11 scoreboard" action={<span className="text-[10px] font-bold uppercase tracking-[0.14em] text-cvc-accent">Provider ready</span>}><MatchupBoard liveOnly /><div className="mt-6 rounded-lg border border-dashed border-cvc-deep/20 bg-cvc-tint p-4 text-sm text-slate-600"><strong className="text-cvc-deep">Provider-neutral adapter:</strong> this display is prepared to receive provider-normalized players, games, and stats without binding CVC to a specific NFL data vendor.</div></Card><div className="grid gap-6 lg:grid-cols-3"><Card title="Live data status"><Metric value="Not connected" label="NFL data provider" /></Card><Card title="Scoring status"><Metric value="Configurable" label="CVC rule engine" /></Card><Card title="Correction window"><Metric value="Commissioner" label="Override authority" /></Card></div></div>; }

function RosterTable({ editable = false }: { editable?: boolean }) { return <div className="overflow-x-auto"><table className="cvc-table"><thead><tr><th>Slot</th><th>Player</th><th>NFL team</th><th>Projection</th><th>Status</th>{editable ? <th /> : null}</tr></thead><tbody>{rosterPreview.map(player => <tr key={player.slot}><td><span className="cvc-slot">{player.slot}</span></td><td className="font-semibold">{player.player}</td><td>{player.team}</td><td>{player.projection}</td><td><StatusPill state={player.status} /></td>{editable ? <td className="text-right"><button className="cvc-mini-button">Move</button></td> : null}</tr>)}</tbody></table></div>; }

function Lineup() { return <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><Card title="Atlas Aces · lineup"><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm text-slate-500">CVC owner workspace uses role-protected roster actions.</p><button className="cvc-button-compact"><Check size={14} /> Save lineup</button></div><RosterTable editable /></Card><div className="space-y-6"><Card title="Matchup outlook"><p className="font-display text-4xl uppercase text-cvc-deep">74.2 <span className="text-cvc-accent">–</span> 69.1</p><p className="mt-2 text-sm text-slate-500">Projection placeholders until a CVC NFL data provider is connected.</p></Card><Card title="Lineup controls"><div className="space-y-3 text-sm text-slate-600"><p>Lineup locks, eligibility, and roster-slot limits come from commissioner configuration.</p><Link className="cvc-text-link" href="/settings">Review CVC roster rules <ChevronRight size={15} /></Link></div></Card></div></div>; }

function Draft({ mode }: { mode: "hub" | "lottery" | "recap" }) { const board = trpc.league.draftBoard.useQuery(); const title = mode === "lottery" ? "Draft lottery order" : mode === "recap" ? "Latest draft recap" : "CVC draft board"; const rows = board.data?.picks ?? []; return <div className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><Card title={title}>{board.isLoading ? <ModuleState label="Loading CVC draft board…" /> : rows.length ? <div className="overflow-x-auto"><table className="cvc-table"><thead><tr><th>Pick</th><th>Franchise</th><th>Selection</th><th>Note</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><span className="cvc-slot">{row.round_number}.{String(row.pick_number).padStart(2, "0")}</span></td><td className="font-semibold">{row.currentFranchise}</td><td>{mode === "recap" ? "Historical selection placeholder" : row.pick_status === "open" ? "Open selection" : "Selection recorded"}</td><td>{row.notes ?? (row.is_protected ? "Protected pick" : "CVC pick")}</td></tr>)}</tbody></table></div> : <ModuleState label="No draft picks have been configured yet." />}</Card><div className="space-y-6"><Card title="Draft controls"><p className="text-sm leading-6 text-slate-600">{board.data ? `${board.data.draft_type} draft · ${board.data.pick_timer_seconds ?? "No"}-second timer · ${board.data.lottery_enabled ? "Lottery enabled" : "Lottery disabled"}` : "Draft settings load from CVC configuration."}</p><Link href="/settings" className="cvc-text-link mt-5">Configure draft settings <ChevronRight size={15} /></Link></Card><Card title="Draft modules"><div className="space-y-3">{["Live draft board", "Pick protection ledger", "Lottery logic", "Draft recap archive"].map((item, index) => <div key={item} className="flex items-center gap-3 text-sm font-medium text-cvc-deep"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-cvc-tint text-[10px] font-bold text-cvc-accent">0{index + 1}</span>{item}</div>)}</div></Card></div></div>; }

function Transactions({ kind }: { kind: "transactions" | "trades" | "free-agents" }) { const activity = trpc.league.activity.useQuery(); const heading = kind === "trades" ? "Trade desk" : kind === "free-agents" ? "FAAB waiver center" : "League activity"; const filtered = (activity.data ?? []).filter(item => kind === "trades" ? item.transaction_type === "trade" : kind === "free-agents" ? item.transaction_type === "waiver" || item.transaction_type === "add" || item.transaction_type === "drop" : true); return <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card title={heading}>{activity.isLoading ? <ModuleState label="Loading CVC activity ledger…" /> : filtered.length ? <div className="divide-y divide-slate-100">{filtered.map(item => <div key={item.id} className="flex gap-4 py-4 first:pt-0 last:pb-0"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-cvc-tint text-xs font-bold text-cvc-accent">{item.transaction_type.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold capitalize text-cvc-deep">{item.transaction_type.replace("_", " ")}</p><p className="mt-1 text-sm text-slate-600">{item.summary}</p><p className="mt-1.5 text-xs text-slate-400">{new Date(item.occurred_at).toLocaleString()}</p></div><StatusPill state={item.status} /></div>)}</div> : <ModuleState label={kind === "trades" ? "No CVC trades have been recorded yet." : kind === "free-agents" ? "No CVC waiver activity has been recorded yet." : "No CVC transaction activity has been recorded yet."} />}</Card><div className="space-y-6"><Card title={kind === "free-agents" ? "Claim workflow" : "Commissioner controls"}><p className="text-sm leading-6 text-slate-600">{kind === "free-agents" ? "Set CVC FAAB budgets, waiver cadence, claim ties, and open free-agent windows in League Configuration." : "Review and override status from the protected commissioner area. All decisions receive an audit record."}</p><Link href="/settings" className="cvc-text-link mt-5">Open configuration <ChevronRight size={15} /></Link></Card><Card title="Audit ready"><div className="flex items-center gap-3"><ShieldCheck className="text-cvc-accent" /><p className="text-sm text-slate-600">Every dynamic CVC action includes an actor, timestamp, source, and commissioner note.</p></div></Card></div></div>; }

function ScheduleResults() { const overview = trpc.league.overview.useQuery(); const rows = overview.data?.matchups ?? []; return <div className="grid gap-6 xl:grid-cols-[1.28fr_0.72fr]"><Card title="CVC schedule board">{rows.length ? <div className="grid gap-4 md:grid-cols-2">{rows.map(row => <div key={row.id} className="cvc-matchup"><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.13em] text-slate-500"><span>{row.week?.label ?? "Schedule week"}</span><StatusPill state={row.result_state} /></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div><p className="font-display text-xl uppercase text-cvc-deep">{row.away}</p><p className="mt-1 text-xs text-slate-500">Away</p></div><strong className="font-display text-3xl text-cvc-deep">{Number(row.away_score).toFixed(1)}<span className="mx-1 text-cvc-accent">:</span>{Number(row.home_score).toFixed(1)}</strong><div className="text-right"><p className="font-display text-xl uppercase text-cvc-deep">{row.home}</p><p className="mt-1 text-xs text-slate-500">Home</p></div></div></div>)}</div> : <MatchupBoard />}</Card><div className="space-y-6"><Card title="Season structure"><p className="text-sm leading-6 text-slate-600">Regular season weeks, matchup cadence, divisions, playoffs, and tiebreakers will be loaded through the commissioner setup flow.</p></Card><Card title="Schedule import"><div className="rounded-lg border border-dashed border-cvc-deep/20 bg-cvc-tint p-4"><p className="text-sm font-semibold text-cvc-deep">CSV-ready import template</p><p className="mt-1 text-xs leading-5 text-slate-500">Week, home franchise, away franchise, game window, and status fields validate before save.</p></div></Card></div></div>; }

function Rundown() { return <div className="grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><Card title="Welcome to CVC"><div className="rounded-xl bg-cvc-deep p-7 text-white"><span className="cvc-eyebrow text-cvc-accent">Commissioner message</span><h2 className="mt-3 font-display text-4xl uppercase leading-none tracking-[0.04em]">The league is<br />ready for you.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/70">CVC starts with a complete league operating system. When the rules and franchise details arrive, they can be entered through the commissioner console rather than built into site code.</p><Link href="/settings" className="cvc-button-light mt-6">Open commissioner setup <ArrowRight size={15} /></Link></div></Card><Card title="Setup progress"><div className="space-y-4">{setupAreas.map((item, index) => <div className="flex gap-3" key={item.title}><span className="font-display text-2xl text-cvc-accent">{item.icon}</span><div><p className="text-sm font-semibold text-cvc-deep">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p></div>{index === 0 ? <StatusPill state="Ready" /> : null}</div>)}</div></Card></div>; }

function NewsOrPlayer({ kind }: { kind: "news" | "player" }) { return <div className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><Card title={kind === "player" ? "Player profile" : "Player news feed"}><div className="space-y-4">{["Data source will be selected by CVC", "Provider attribution appears with each item", "Commissioner can define refresh and retention rules"].map((item, index) => <div className="rounded-lg border border-slate-100 p-4" key={item}><div className="flex items-center justify-between"><p className="text-sm font-semibold text-cvc-deep">{kind === "player" && index === 0 ? "Player Placeholder" : item}</p><span className="text-xs text-slate-400">Foundation</span></div><p className="mt-2 text-sm leading-6 text-slate-500">This component remains intentionally source-neutral while the CVC live data provider is evaluated.</p></div>)}</div></Card><Card title="Adapter status"><p className="font-display text-3xl uppercase text-cvc-deep">Not bound</p><p className="mt-2 text-sm leading-6 text-slate-600">The data adapter accepts normalized player, news, game, and stat records; a provider can be connected without redesigning this screen.</p></Card></div>; }

function Informational({ kind }: { kind: "history" | "playoffs" | "rules" | "nfl-sites" | "money" }) { const module = pageMeta[kind]; return <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card title={module.title}><div className="rounded-xl bg-cvc-tint p-7"><p className="font-display text-3xl uppercase text-cvc-deep">CVC {kind === "rules" ? "rulebook" : kind === "money" ? "league ledger" : "archive module"}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-600">This module is foundation-ready and intentionally uses no actual CVC history, policy, or financial information. Commissioner-entered records will replace all placeholders when the league is configured.</p>{kind === "rules" ? <div className="mt-6 space-y-3">{["Scoring and roster policy", "Transactions, FAAB, and trades", "Playoffs, tiebreakers, and commissioner authority"].map((item, index) => <div className="flex items-center justify-between rounded-lg bg-white px-4 py-3 text-sm font-medium text-cvc-deep" key={item}><span>{item}</span><span className="text-xs text-slate-400">Version 0{index + 1}</span></div>)}</div> : <div className="mt-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-cvc-accent"><BookOpen size={18} /></span><span className="text-sm font-medium text-cvc-deep">Commissioner-managed content and records</span></div>}</div></Card><Card title="Commissioner action"><p className="text-sm leading-6 text-slate-600">Use League Configuration to publish approved CVC content, define privacy settings, and establish the history or finance record model for this season.</p><Link href="/settings" className="cvc-text-link mt-5">Open configuration <ChevronRight size={15} /></Link></Card></div>; }

function Rosters() { return <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card title="CVC franchises"><div className="grid gap-3 sm:grid-cols-2">{franchises.map(team => <Link href={`/lineup/${team.id}`} className="cvc-franchise-card" key={team.id}><span className="h-2.5 w-2.5 rounded-full" style={{ background: team.color }} /><div className="min-w-0 flex-1"><p className="font-display text-xl uppercase text-cvc-deep">{team.name}</p><p className="mt-1 text-xs text-slate-500">{team.owner} · {team.division} division</p></div><ChevronRight size={17} className="text-slate-400" /></Link>)}</div></Card><Card title="Roster model"><p className="text-sm leading-6 text-slate-600">CVC roster slots, salary/keeper attributes, player eligibility, and owner affiliation will all be configuration-driven.</p><div className="mt-5"><Metric value="Placeholder" label="Franchise data" /></div></Card></div>; }

function Settings() { const [active, setActive] = useState("teams"); const setup = trpc.league.setupSummary.useQuery(); const content = useMemo(() => ({ teams: ["Franchise name", "Abbreviation", "Division", "Owner membership"], scoring: ["Roster slots", "Scoring categories", "Bonuses and penalties", "Lineup locks"], schedule: ["Regular season weeks", "Matchups", "Playoff seeding", "Tiebreakers"], rules: ["Rule documents", "Version and publish date", "Public visibility", "Commissioner notes"], finance: ["League dues", "Payout schedule", "Balances", "Private access"] })[active] ?? [], [active]); return <div className="grid gap-6 xl:grid-cols-[0.38fr_1fr]"><Card title="Setup modules"><div className="space-y-1">{[["teams", "Teams & owners"], ["scoring", "Scoring & rosters"], ["schedule", "Schedule & playoffs"], ["rules", "Rules & content"], ["finance", "Finance"]].map(([key, label]) => <button key={key} className={cn("cvc-config-link", active === key && "is-active")} onClick={() => setActive(key)}>{label}<ChevronRight size={15} /></button>)}</div><div className="mt-5 rounded-lg bg-cvc-tint p-3 text-xs leading-5 text-slate-500">CVC data layer: {setup.isLoading ? "checking schema…" : `${setup.data?.filter(item => item.count > 0).length ?? 0} configured modules ready`}.</div></Card><Card title={`Configure ${active}`} action={<span className="text-[10px] font-bold uppercase tracking-[0.13em] text-cvc-accent">Commissioner form</span>}><div className="grid gap-4 sm:grid-cols-2">{content.map(label => <label key={label} className="cvc-field"><span>{label}</span><input placeholder={`Enter ${label.toLowerCase()}`} /></label>)}</div><div className="mt-6 flex flex-wrap gap-3"><button className="cvc-button-compact"><Plus size={14} /> Add placeholder</button><label className="cvc-button-secondary cursor-pointer"><Upload size={14} /> Import CSV<input className="sr-only" type="file" accept=".csv" /></label><button className="cvc-button-secondary">Download template</button></div><div className="mt-6 rounded-lg border border-dashed border-cvc-deep/20 p-4 text-sm text-slate-600"><strong className="text-cvc-deep">Connected data layer:</strong> commissioner saves validate against the CVC Supabase schema and create an audit entry. Your current account must first be mapped to a commissioner role in CVC.</div></Card></div>; }

export function PublicFranchiseLineup() { const [, params] = useRoute("/lineup/:franchiseId"); const franchise = franchises.find(item => item.id === params?.franchiseId); return <LeagueLayout><div className="mb-8"><div className="cvc-eyebrow"><UsersRound size={14} /> Public franchise view</div><h1 className="mt-2 font-display text-5xl uppercase leading-none tracking-[0.04em] text-white sm:text-6xl">{franchise?.name ?? "Franchise lineup"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-cvc-muted">Public lineup, roster, and matchup information. Owner actions remain protected.</p></div><Card title={`${franchise?.name ?? "Franchise"} roster`}><RosterTable /></Card></LeagueLayout>; }

export default function LeaguePage({ kind }: { kind: PageKind }) {
  let body: React.ReactNode;
  if (kind === "standings") body = <Standings />;
  else if (kind === "live") body = <LiveScoring />;
  else if (kind === "lineup") body = <Lineup />;
  else if (kind === "draft" || kind === "draft-lottery" || kind === "draft-recap") body = <Draft mode={kind === "draft" ? "hub" : kind === "draft-lottery" ? "lottery" : "recap"} />;
  else if (kind === "transactions" || kind === "trades" || kind === "free-agents") body = <Transactions kind={kind} />;
  else if (kind === "results") body = <ScheduleResults />;
  else if (kind === "rundown") body = <Rundown />;
  else if (kind === "news" || kind === "player") body = <NewsOrPlayer kind={kind} />;
  else if (kind === "rosters") body = <Rosters />;
  else if (kind === "settings") body = <CommissionerPanel />;
  else body = <Informational kind={kind as "history" | "playoffs" | "rules" | "nfl-sites" | "money"} />;
  return <LeagueLayout><PageHeader kind={kind} action={kind === "standings" ? <Link href="/settings" className="cvc-button-compact"><Settings2 size={14} /> Configure CVC</Link> : undefined} />{body}</LeagueLayout>;
}
