import { useCvcOwnerAuth } from "@/hooks/useCvcOwnerAuth";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ChevronDown, Lock, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link, useLocation } from "wouter";

export default function Login() {
  const { owner, isAuthenticated, loading, logout, isSigningOut } = useCvcOwnerAuth();
  const owners = trpc.ownerAuth.owners.useQuery();
  const utils = trpc.useUtils();
  const [, setLocation] = useLocation();
  const [ownerId, setOwnerId] = useState("");
  const [pin, setPin] = useState("");
  const signIn = trpc.ownerAuth.signIn.useMutation({ onSuccess: async session => { await Promise.all([utils.ownerAuth.session.invalidate(), utils.league.access.invalidate(), utils.league.myFranchise.invalidate()]); setLocation(session.franchise ? "/lineup" : "/settings"); } });
  useEffect(() => { if (!loading && isAuthenticated && owner) setLocation(owner.franchise ? "/lineup" : "/settings"); }, [isAuthenticated, loading, owner, setLocation]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (ownerId && pin.length === 4) signIn.mutate({ ownerId, pin }); }

  return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-cvc-ink px-4 py-8"><div className="cvc-stadium-layer" aria-hidden="true" /><div className="relative z-10 w-full max-w-[440px]">
    <div className="mb-8 text-center"><div className="mx-auto mb-4 flex h-[76px] w-[76px] items-center justify-center rounded-xl border-[3px] border-cvc-accent bg-cvc-deep"><img src="/brand/header-crest.png" alt="CVC Fantasy Football" className="h-16 w-16 object-contain" /></div><h1 className="font-display text-4xl uppercase tracking-[0.06em] text-white sm:text-5xl">CVC Fantasy Football</h1><p className="mt-2 text-sm tracking-[0.04em] text-white/65">2026 Season</p></div>
    <section className="overflow-hidden rounded-xl bg-white shadow-2xl"><div className="h-1.5 bg-cvc-accent" /><div className="p-7 sm:p-8">{loading ? <p className="text-sm text-slate-500">Checking CVC owner session…</p> : isAuthenticated && owner ? <div className="space-y-4"><p className="text-sm text-slate-600">Signed in as <strong>{owner.displayName}</strong>.</p><Link href={owner.franchise ? "/lineup" : "/settings"} className="cvc-button w-full justify-center">Open {owner.franchise ? "my lineup" : "commissioner settings"} <ArrowRight size={16} /></Link><button className="cvc-button-secondary w-full justify-center" disabled={isSigningOut} onClick={() => logout()}>Sign out</button></div> : <form onSubmit={submit} className="space-y-5"><div><label className="mb-2 block font-display text-sm uppercase tracking-[0.08em] text-cvc-deep">Select your team</label><div className="relative"><select value={ownerId} onChange={event => setOwnerId(event.target.value)} disabled={owners.isLoading} className="w-full appearance-none rounded-lg border border-cvc-deep/20 bg-white px-3 py-3 pr-10 text-sm text-cvc-deep outline-none focus:border-cvc-accent" required><option value="">{owners.isLoading ? "Loading teams…" : "Select Your Team"}</option>{owners.data?.map(item => <option key={item.id} value={item.id}>{item.franchise ? `${item.franchise.name} — ${item.displayName}` : `Administrator — ${item.displayName}`}</option>)}</select><ChevronDown size={17} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" /></div>{owners.error ? <p className="mt-2 text-xs text-red-700">The team list is unavailable. Please refresh and try again.</p> : null}</div><div><label className="mb-2 block font-display text-sm uppercase tracking-[0.08em] text-cvc-deep">Enter your PIN</label><div className="relative"><input value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, "").slice(0, 4))} type="password" inputMode="numeric" autoComplete="current-password" placeholder="Enter PIN" maxLength={4} className="w-full rounded-lg border border-cvc-deep/20 bg-white px-3 py-3 pr-10 text-lg tracking-[0.28em] text-cvc-deep outline-none focus:border-cvc-accent" required /><Lock size={16} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" /></div></div>{signIn.error ? <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{signIn.error.message}</p> : null}<button type="submit" disabled={!ownerId || pin.length !== 4 || signIn.isPending} className="cvc-button w-full justify-center">{signIn.isPending ? "Signing in…" : <><ShieldCheck size={16} /> Sign in</>}</button></form>}</div></section>
    <p className="mt-7 text-center text-xs text-white/40">CVC owner access is secured by an independent league PIN session.</p><Link href="/standings" className="mt-4 flex items-center justify-center gap-2 text-xs font-bold uppercase tracking-[0.1em] text-white/70 hover:text-white">Return to public league view <ArrowRight size={13} /></Link>
  </div></div>;
}
