import { LeagueLayout } from "@/components/LeagueLayout";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";

function rightLabel(rightType: string) { return rightType.replaceAll("_", " "); }

export default function Protections() {
  const mine = trpc.league.myFranchise.useQuery(); const access = trpc.league.access.useQuery(); const utils = trpc.useUtils();
  const roster = trpc.league.franchiseRoster.useQuery({ franchiseId: mine.data?.id ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(mine.data?.id) });
  const refresh = async () => Promise.all([utils.league.franchiseRoster.invalidate(), utils.league.activity.invalidate(), utils.league.freeAgents.invalidate(), utils.auction.eligiblePlayers.invalidate()]);
  const cutPlayer = trpc.league.cutContractPlayer.useMutation({ onSuccess: refresh }); const franchiseTag = trpc.league.assignFranchiseTag.useMutation({ onSuccess: refresh }); const transitionTag = trpc.league.assignTransitionTag.useMutation({ onSuccess: refresh }); const restrictedRight = trpc.league.assignRestrictedRight.useMutation({ onSuccess: refresh });
  const players = [...(roster.data?.players ?? [])].sort((a, b) => (a.player?.display_name ?? "").localeCompare(b.player?.display_name ?? ""));
  const busy = cutPlayer.isPending || franchiseTag.isPending || transitionTag.isPending || restrictedRight.isPending; const actionError = cutPlayer.error ?? franchiseTag.error ?? transitionTag.error ?? restrictedRight.error; const franchiseId = mine.data?.id;
  const activeRights = players.filter(item => item.rights.length > 0).length; const contracted = players.filter(item => item.contract).length;
  function confirmAction(message: string, action: () => void) { if (window.confirm(message)) action(); }

  return <LeagueLayout><div className="mx-auto max-w-[1100px]">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="cvc-eyebrow"><ShieldCheck size={14} /> Owner protections</div><h1 className="mt-2 font-display text-5xl uppercase leading-none tracking-[0.04em] text-white sm:text-6xl">Protections</h1><p className="mt-3 text-sm text-cvc-muted">{mine.data?.name ?? "Your franchise"} · Review live contracts and make official CVC protection decisions.</p></div><div className="rounded-lg border border-cvc-accent/40 bg-cvc-accent/10 px-4 py-3 text-right"><p className="font-display text-xs uppercase tracking-[0.1em] text-cvc-accent">Decision status</p><p className="mt-1 text-sm text-white">Changes save immediately to CVC league records</p></div></div>
    {actionError ? <div role="alert" className="mb-5 flex items-center gap-3 rounded-lg border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800"><AlertTriangle size={17} /> {actionError.message}</div> : null}
    <section className="overflow-hidden rounded-xl bg-white shadow-xl"><div className="h-1.5 bg-cvc-accent" /><div className="bg-cvc-deep px-5 py-4 text-white"><p className="font-display text-2xl uppercase tracking-[0.06em]">{mine.data?.name ?? "My franchise"} contract decisions</p><p className="mt-1 text-sm text-white/60">Cut, tag, or designate matching rights before the next CVC auction cycle.</p></div><div className="grid grid-cols-2 divide-x divide-y divide-slate-200 border-b border-slate-200 sm:grid-cols-4 sm:divide-y-0"><Metric label="Contracted" value={contracted} /><Metric label="Active rights" value={activeRights} /><Metric label="Available" value={Math.max(0, contracted - activeRights)} /><Metric label="Cut penalty" value="$0" accent /></div>
      <div className="overflow-x-auto"><table className="min-w-[1060px] w-full text-left"><thead className="bg-[#edf4ee]"><tr className="font-display text-xs uppercase tracking-[0.07em] text-cvc-deep"><th className="px-5 py-4">Player</th><th className="px-3 py-4">Contract</th><th className="px-3 py-4">Current right</th><th className="px-5 py-4 text-right">Protection decision</th></tr></thead><tbody>{mine.isLoading || roster.isLoading ? <tr><td colSpan={4} className="px-5 py-8 text-center text-sm text-slate-500">Loading protection candidates…</td></tr> : roster.error ? <tr><td colSpan={4} className="px-5 py-8 text-center text-sm text-red-700">{roster.error.message}</td></tr> : players.length ? players.map(item => {
        const marker = (item.contract?.source_marker ?? "").toUpperCase(); const rightText = item.rights.length ? item.rights.map(right => rightLabel(right.right_type)).join(", ") : item.contract?.contract_status ?? item.roster_state; const hasActiveRight = item.rights.length > 0; const available = Boolean(item.contract) && !hasActiveRight && Boolean(franchiseId); const taggedSalary = item.contract ? Number(item.contract.salary) + 1 : 0; const twoYear = taggedSalary < 10; const playerName = item.player?.display_name ?? "this player";
        return <tr key={item.id} className="border-t border-slate-200 align-top hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-cvc-deep font-display text-xs text-cvc-accent">{item.player?.position ?? "—"}</span><div><p className="font-semibold text-cvc-deep">{playerName}</p><p className="mt-0.5 text-xs text-slate-500">{item.player?.position ?? "—"} · {item.player?.nfl_team ?? "FA"}</p></div></div></td><td className="px-3 py-4"><p className="font-semibold text-cvc-deep">{item.contract ? `$${Number(item.contract.salary).toFixed(0)}` : "—"}</p><p className="mt-1 text-xs text-slate-500">{item.contract?.source_marker ?? item.contract?.expires_year ?? "—"}</p></td><td className="px-3 py-4"><span className={hasActiveRight ? "rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-emerald-700" : "text-xs capitalize text-slate-500"}>{rightText}</span></td><td className="px-5 py-4"><div className="flex max-w-[500px] flex-wrap justify-end gap-2"><Action disabled={!available || busy} tone="cut" label="Cut · no penalty" onClick={() => confirmAction(`Release ${playerName}? This is final, carries no contract penalty, and makes the player an unrestricted free agent.`, () => cutPlayer.mutate({ franchiseId: franchiseId!, playerId: item.player_id }))} /><Action disabled={!available || !twoYear || busy} tone="gold" label="Franchise · 2 yr" onClick={() => confirmAction(`Assign a two-year franchise tag to ${playerName}? Salary increases by $1.`, () => franchiseTag.mutate({ franchiseId: franchiseId!, playerId: item.player_id, contractYears: 2 }))} /><Action disabled={!available || twoYear || busy} tone="gold" label="Franchise · 3 yr" onClick={() => confirmAction(`Assign a three-year franchise tag to ${playerName}? Salary increases by $1.`, () => franchiseTag.mutate({ franchiseId: franchiseId!, playerId: item.player_id, contractYears: 3 }))} /><Action disabled={!available || busy} tone="blue" label="Transition" onClick={() => confirmAction(`Assign a one-year transition tag to ${playerName}? Under-$10 contracts double; $10-and-over contracts add $10.`, () => transitionTag.mutate({ franchiseId: franchiseId!, playerId: item.player_id }))} /><Action disabled={!available || !marker.includes("R") || busy} tone="violet" label="Rookie right" onClick={() => confirmAction(`Assign rookie matching rights to ${playerName}?`, () => restrictedRight.mutate({ franchiseId: franchiseId!, playerId: item.player_id, rightType: "rookie_match" }))} /><Action disabled={!available || !marker.includes("W") || busy} tone="green" label="Waiver right" onClick={() => confirmAction(`Assign waiver matching rights to ${playerName}?`, () => restrictedRight.mutate({ franchiseId: franchiseId!, playerId: item.player_id, rightType: "waiver_match", waiverEligibilityOverride: Boolean(access.data?.isCommissioner) }))} /></div></td></tr>;
      }) : <tr><td colSpan={4} className="px-5 py-8 text-center text-sm text-slate-500">No rostered players are available for protection review.</td></tr>}</tbody></table></div>
      <div className="m-5 flex gap-3 rounded-lg border border-cvc-accent/40 bg-cvc-accent/10 p-4 text-sm leading-6 text-cvc-deep"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-cvc-accent" /><p><strong>CVC protection rules:</strong> A franchise may designate one under-$10 and one $10-and-over franchise player. Franchise salary increases by $1; the resulting tier determines a two-year or three-year term. Transition tags last one year. Eligible rookie and waiver rights pause later auction awards for a commissioner match decision.</p></div>
    </section></div></LeagueLayout>;
}

function Metric({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className="px-5 py-4"><p className="font-display text-[11px] uppercase tracking-[0.09em] text-slate-500">{label}</p><p className={accent ? "mt-1 font-display text-3xl text-cvc-accent" : "mt-1 font-display text-3xl text-cvc-deep"}>{value}</p></div>; }
function Action({ label, tone, disabled, onClick }: { label: string; tone: "cut" | "gold" | "blue" | "violet" | "green"; disabled: boolean; onClick: () => void }) { const styles = { cut: "border-red-300 bg-red-50 text-red-800 hover:bg-red-100", gold: "border-cvc-gold/50 bg-cvc-gold/10 text-cvc-deep hover:bg-cvc-gold/20", blue: "border-sky-300 bg-sky-50 text-sky-800 hover:bg-sky-100", violet: "border-violet-300 bg-violet-50 text-violet-800 hover:bg-violet-100", green: "border-emerald-300 bg-emerald-50 text-emerald-800 hover:bg-emerald-100" }; return <button type="button" disabled={disabled} onClick={onClick} className={`rounded border px-2 py-1 text-[10px] font-bold uppercase tracking-wide transition disabled:cursor-not-allowed disabled:opacity-35 ${styles[tone]}`}>{label}</button>; }
