import { LeagueLayout } from "@/components/LeagueLayout";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

function rightLabel(rightType: string) { return rightType.replaceAll("_", " "); }

type Decision = "cut" | "franchise_2" | "franchise_3" | "transition" | "rookie_match" | "waiver_match";

type ProtectionProfile = { espnHeadshot?: string };
const profileCache = new Map<string, ProtectionProfile | null>();
const profileKey = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
const normalizedPosition = (value: string | null | undefined) => ({ KI: "K", DE: "DST", DEF: "DST" }[(value ?? "").toUpperCase()] ?? (value ?? "").toUpperCase());
const positionOrder: Record<string, number> = { QB: 0, RB: 1, WR: 2, TE: 3, K: 4, DST: 5 };
const normalizeTeam = (team: string | null | undefined) => ({ kan: "kc", tam: "tb", arz: "ari", jax: "jac", was: "wsh" }[(team ?? "").toLowerCase()] ?? (team ?? "").toLowerCase());
const teamLogo = (team: string | null | undefined) => `https://a.espncdn.com/i/teamlogos/nfl/500/${normalizeTeam(team)}.png`;

function useProtectionProfiles(players: any[]) {
  const signature = players.map(item => item.player?.display_name ?? "").sort().join("|"); const [profiles, setProfiles] = useState<Record<string, ProtectionProfile | null>>({});
  useEffect(() => { let active = true; const names = Array.from(new Set(players.filter(item => normalizedPosition(item.player?.position) !== "DST").map(item => item.player?.display_name).filter(Boolean))).slice(0, 24); void Promise.all(names.map(async (name: string) => { const key = profileKey(name); if (profileCache.has(key)) return [key, profileCache.get(key) ?? null] as [string, ProtectionProfile | null]; try { const response = await fetch(`/api/tank01/getNFLPlayerInfo?playerName=${encodeURIComponent(name)}&getStats=false`); const payload = await response.json() as { body?: ProtectionProfile[] }; const profile = payload.body?.[0] ?? null; profileCache.set(key, profile); return [key, profile] as [string, ProtectionProfile | null]; } catch { profileCache.set(key, null); return [key, null] as [string, ProtectionProfile | null]; } })).then(entries => { if (active) setProfiles(Object.fromEntries(entries)); }); return () => { active = false; }; }, [signature]);
  return profiles;
}

function PositionBubble({ player, profile }: { player: { display_name?: string | null; position?: string | null; nfl_team?: string | null } | null | undefined; profile: ProtectionProfile | null | undefined }) { const [failed, setFailed] = useState(false); const position = normalizedPosition(player?.position); const source = position === "DST" ? teamLogo(player?.nfl_team) : profile?.espnHeadshot; return <span className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-full bg-cvc-deep font-display text-xs text-cvc-accent">{source && !failed ? <img src={source} alt="" className={position === "DST" ? "h-8 w-8 object-contain" : "h-full w-full object-cover object-top"} onError={() => setFailed(true)} /> : position || "—"}</span>; }

function Metric({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className="px-5 py-4"><p className="font-display text-[11px] uppercase tracking-[0.09em] text-slate-500">{label}</p><p className={accent ? "mt-1 font-display text-3xl text-cvc-accent" : "mt-1 font-display text-3xl text-cvc-deep"}>{value}</p></div>; }

export default function Protections() {
  const mine = trpc.league.myFranchise.useQuery(); const access = trpc.league.access.useQuery(); const utils = trpc.useUtils();
  const roster = trpc.league.franchiseRoster.useQuery({ franchiseId: mine.data?.id ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(mine.data?.id) });
  const refresh = async () => Promise.all([utils.league.franchiseRoster.invalidate(), utils.league.activity.invalidate(), utils.league.freeAgents.invalidate(), utils.auction.eligiblePlayers.invalidate()]);
  const cutPlayer = trpc.league.cutContractPlayer.useMutation({ onSuccess: refresh }); const franchiseTag = trpc.league.assignFranchiseTag.useMutation({ onSuccess: refresh }); const transitionTag = trpc.league.assignTransitionTag.useMutation({ onSuccess: refresh }); const restrictedRight = trpc.league.assignRestrictedRight.useMutation({ onSuccess: refresh }); const undoProtection = trpc.league.undoProtection.useMutation({ onSuccess: refresh }); const restoreCut = trpc.league.restoreCutPlayer.useMutation({ onSuccess: refresh });
  const players = [...(roster.data?.players ?? [])].sort((a, b) => positionOrder[normalizedPosition(a.player?.position)] - positionOrder[normalizedPosition(b.player?.position)] || Number(b.contract?.salary ?? 0) - Number(a.contract?.salary ?? 0) || (a.player?.display_name ?? "").localeCompare(b.player?.display_name ?? ""));
  const profiles = useProtectionProfiles(players);
  const busy = cutPlayer.isPending || franchiseTag.isPending || transitionTag.isPending || restrictedRight.isPending || undoProtection.isPending || restoreCut.isPending; const actionError = cutPlayer.error ?? franchiseTag.error ?? transitionTag.error ?? restrictedRight.error ?? undoProtection.error ?? restoreCut.error; const franchiseId = mine.data?.id;
  const activeRights = players.filter(item => item.rights.length > 0).length; const contracted = players.filter(item => item.contract).length;
  const franchiseTwoTaken = players.some(item => item.rights.some((right: any) => right.right_type === "franchise" && (right.contract_years === 2 || right.metadata?.term_tier === "two_year")));
  const franchiseThreeTaken = players.some(item => item.rights.some((right: any) => right.right_type === "franchise" && (right.contract_years === 3 || right.metadata?.term_tier === "three_year")));

  function confirmAction(message: string, action: () => void) { if (window.confirm(message)) action(); }
  function applyDecision(decision: Decision, item: any) {
    if (!franchiseId) return;
    const playerName = item.player?.display_name ?? "this player";
    const salary = Number(item.contract?.salary ?? 0); const priorSalary = Math.max(0, salary - 1); const tierTwo = priorSalary < 10; const transitionSalary = tierTwo ? priorSalary * 2 : priorSalary + 10;
    if (decision === "cut") return confirmAction(`Release ${playerName}? This is final, carries no contract penalty, and makes the player an unrestricted free agent.`, () => cutPlayer.mutate({ franchiseId, playerId: item.player_id }));
    if (decision === "franchise_2") return confirmAction(`Assign the two-year franchise contract to ${playerName}? The current 2026 salary remains $${salary.toFixed(0)}.`, () => franchiseTag.mutate({ franchiseId, playerId: item.player_id, contractYears: 2 }));
    if (decision === "franchise_3") return confirmAction(`Assign the three-year franchise contract to ${playerName}? The current 2026 salary remains $${salary.toFixed(0)}.`, () => franchiseTag.mutate({ franchiseId, playerId: item.player_id, contractYears: 3 }));
    if (decision === "transition") return confirmAction(`Transition ${playerName} for one season at $${transitionSalary.toFixed(0)}? This designation cannot be used again.`, () => transitionTag.mutate({ franchiseId, playerId: item.player_id }));
    if (decision === "rookie_match") return confirmAction(`Assign rookie matching rights to ${playerName}?`, () => restrictedRight.mutate({ franchiseId, playerId: item.player_id, rightType: "rookie_match" }));
    return confirmAction(`Assign waiver matching rights to ${playerName}?`, () => restrictedRight.mutate({ franchiseId, playerId: item.player_id, rightType: "waiver_match", waiverEligibilityOverride: Boolean(access.data?.isCommissioner) }));
  }

  return <LeagueLayout><div className="mx-auto max-w-[1100px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="cvc-eyebrow"><ShieldCheck size={14} /> Owner protections</div><h1 className="mt-2 font-display text-5xl uppercase leading-none tracking-[0.04em] text-white sm:text-6xl">Protections</h1><p className="mt-3 text-sm text-cvc-muted">{mine.data?.name ?? "Your franchise"} · Review live contracts and make official CVC protection decisions.</p></div><div className="rounded-lg border border-cvc-accent/40 bg-cvc-accent/10 px-4 py-3 text-right"><p className="font-display text-xs uppercase tracking-[0.1em] text-cvc-accent">Decision status</p><p className="mt-1 text-sm text-white">Each dropdown shows only CVC-eligible decisions</p></div></div>
    {actionError ? <div role="alert" className="mb-5 flex items-center gap-3 rounded-lg border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800"><AlertTriangle size={17} /> {actionError.message}</div> : null}
    <section className="overflow-hidden rounded-xl bg-white shadow-xl"><div className="h-1.5 bg-cvc-accent" /><div className="bg-cvc-deep px-5 py-4 text-white"><p className="font-display text-2xl uppercase tracking-[0.06em]">{mine.data?.name ?? "My franchise"} contract decisions</p><p className="mt-1 text-sm text-white/60">Choose one eligible decision for a player before the next CVC auction cycle.</p></div><div className="grid grid-cols-2 divide-x divide-y divide-slate-200 border-b border-slate-200 sm:grid-cols-4 sm:divide-y-0"><Metric label="Contracted" value={contracted} /><Metric label="Active rights" value={activeRights} /><Metric label="Available" value={Math.max(0, contracted - activeRights)} /><Metric label="Cut penalty" value="$0" accent /></div>
      <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left"><thead className="bg-[#edf4ee]"><tr className="font-display text-xs uppercase tracking-[0.07em] text-cvc-deep"><th className="px-5 py-4">Player</th><th className="px-3 py-4">Salary</th><th className="px-3 py-4">Year</th><th className="px-3 py-4">Status</th><th className="px-3 py-4">Current right</th><th className="px-5 py-4 text-right">Protection decision</th></tr></thead><tbody>{mine.isLoading || roster.isLoading ? <tr><td colSpan={6} className="px-5 py-8 text-center text-sm text-slate-500">Loading protection candidates…</td></tr> : roster.error ? <tr><td colSpan={6} className="px-5 py-8 text-center text-sm text-red-700">{roster.error.message}</td></tr> : players.length ? players.map(item => {
        const rightText = item.rights.length ? item.rights.map(right => rightLabel(right.right_type)).join(", ") : item.contract?.contract_status ?? item.roster_state; const hasActiveRight = item.rights.length > 0; const salary = Number(item.contract?.salary ?? 0); const priorSalary = Math.max(0, salary - 1); const tierTwo = priorSalary < 10; const playerName = item.player?.display_name ?? "this player";
        const actionLabels: Record<Decision, string> = { cut: "Cut · no penalty", franchise_2: "Franchise · 2 yr", franchise_3: "Franchise · 3 yr", transition: `Transition · $${(tierTwo ? priorSalary * 2 : priorSalary + 10).toFixed(0)}`, rookie_match: "Rookie right", waiver_match: "Waiver right" };
        const options: Array<{ value: Decision; label: string }> = (item.protectionEligibility?.availableActions ?? []).map((value: Decision) => ({ value, label: actionLabels[value] })); const available = Boolean(franchiseId) && options.length > 0;
        const status = item.contract?.source_marker?.trim().toUpperCase() || (item.rights.some((right: any) => right.right_type === "franchise") ? "F" : item.rights.some((right: any) => right.right_type === "transition") ? "T" : item.rights.some((right: any) => right.right_type === "rookie_match") ? "R" : item.rights.some((right: any) => right.right_type === "waiver_match") ? "W" : "");
        return <tr key={item.id} className="border-t border-slate-200 align-top hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><PositionBubble player={item.player} profile={profiles[profileKey(playerName)]} /><div><p className="font-semibold text-cvc-deep">{playerName}</p><p className="mt-0.5 text-xs text-slate-500">{normalizedPosition(item.player?.position) || "—"} · {item.player?.nfl_team ?? "FA"}</p></div></div></td><td className="px-3 py-4 font-semibold text-cvc-deep">{item.contract ? `$${salary.toFixed(0)}` : "—"}</td><td className="px-3 py-4 text-sm text-slate-600">{item.contract?.expires_year ?? "—"}</td><td className="px-3 py-4">{status ? <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-cvc-deep">{status}</span> : null}</td><td className="px-3 py-4"><span className={hasActiveRight ? "rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-emerald-700" : "text-xs capitalize text-slate-500"}>{rightText}</span></td><td className="px-5 py-4 text-right">{hasActiveRight ? <button disabled={busy || !franchiseId} onClick={() => confirmAction(`Undo the saved protection for ${playerName}?`, () => undoProtection.mutate({ franchiseId, rightId: item.rights[0].id }))} className="rounded-md border border-amber-400 px-3 py-2 text-xs font-bold uppercase tracking-[0.06em] text-amber-800 disabled:opacity-50">Undo protection</button> : <select aria-label={`Protection decision for ${playerName}`} defaultValue="" disabled={!available || busy} onChange={event => { const decision = event.target.value as Decision; event.target.value = ""; if (decision) applyDecision(decision, item); }} className="min-w-48 rounded-md border border-cvc-deep/20 bg-white px-3 py-2 text-sm font-semibold text-cvc-deep outline-none focus:border-cvc-accent disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400"><option value="">{available ? "Choose decision" : "No eligible decision"}</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>}</td></tr>;
      }) : <tr><td colSpan={6} className="px-5 py-8 text-center text-sm text-slate-500">No rostered players are available for protection review.</td></tr>}</tbody></table></div>
      <div className="grid gap-5 border-t border-slate-200 bg-slate-50 p-5 lg:grid-cols-2"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl uppercase text-cvc-deep">Cut Players</h2><span className="text-xs font-bold uppercase tracking-[0.08em] text-slate-500">{roster.data?.cutPlayers?.length ?? 0}</span></div>{roster.data?.cutPlayers?.length ? <div className="space-y-2">{roster.data.cutPlayers.map((item: any) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-red-100 bg-white p-3"><div className="flex items-center gap-2"><PositionBubble player={item.player} profile={profiles[profileKey(item.player?.display_name ?? "")]} /><div><p className="font-semibold text-cvc-deep">{item.player?.display_name}</p><p className="text-xs text-slate-500">{normalizedPosition(item.player?.position)} · ${Number(item.contract?.salary ?? 0).toFixed(0)} · {item.contract?.expires_year ?? "—"}</p></div></div><button disabled={busy || !franchiseId} onClick={() => confirmAction(`Restore ${item.player?.display_name ?? "this player"} to your roster?`, () => restoreCut.mutate({ franchiseId, playerId: item.player_id }))} className="rounded-md border border-cvc-deep/20 px-2.5 py-1.5 text-xs font-bold uppercase tracking-[0.06em] text-cvc-deep disabled:opacity-50">Undo cut</button></div>)}</div> : <p className="rounded-lg border border-dashed border-slate-300 bg-white px-4 py-5 text-sm text-slate-500">No players have been cut from this franchise.</p>}</section><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl uppercase text-cvc-deep">Restricted Players</h2><span className="text-xs font-bold uppercase tracking-[0.08em] text-slate-500">{roster.data?.restrictedPlayers?.length ?? 0}</span></div>{roster.data?.restrictedPlayers?.length ? <div className="space-y-2">{roster.data.restrictedPlayers.map((item: any) => <div key={item.id} className="flex items-center gap-2 rounded-lg border border-emerald-100 bg-white p-3"><PositionBubble player={item.player} profile={profiles[profileKey(item.player?.display_name ?? "")]} /><div><p className="font-semibold text-cvc-deep">{item.player?.display_name}</p><p className="text-xs text-slate-500">{item.rights.map((right: any) => rightLabel(right.right_type)).join(", ")} · ${Number(item.contract?.salary ?? 0).toFixed(0)}</p></div></div>)}</div> : <p className="rounded-lg border border-dashed border-slate-300 bg-white px-4 py-5 text-sm text-slate-500">No active restricted-player decisions.</p>}</section></div>
      <div className="m-5 flex gap-3 rounded-lg border border-cvc-accent/40 bg-cvc-accent/10 p-4 text-sm leading-6 text-cvc-deep"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-cvc-accent" /><p><strong>CVC protection rules:</strong> Two-year/under-$10 transitions double the salary for one season and may later be franchised but not transitioned again. Three-year/$10-and-over transitions add $10 for one season and cannot later be franchised or transitioned. Each franchise may hold one two-year and one three-year franchise designation; franchised players may be re-franchised after expiry but cannot be transitioned.</p></div>
    </section></div></LeagueLayout>;
}
