import { BookOpenCheck, Gavel, ShieldCheck, Trophy } from "lucide-react";
import { trpc } from "@/lib/trpc";

const policies = [
  { title: "League Format", content: "Ten CVC franchises compete in East and West divisions. Both division winners receive playoff byes; four wild-card teams complete the six-team bracket." },
  { title: "Roster & Lineup", content: "Every franchise must carry at least 15 and no more than 22 players. CVC uses commissioner-configured roster slots; individual players lock at NFL kickoff for live scoring." },
  { title: "Auction Room", items: ["Starting budgets may not exceed the confirmed $115 cap.", "Regular auction eligibility is limited to unrostered, non-rookie players.", "Any legal bid is allowed; commissioner controls nominations and final awards.", "A team must retain the $1-per-player reserve needed to reach the 15-player minimum."] },
  { title: "Protections & Rights", items: ["Existing active contracts remain on the franchise roster until released or expired.", "One franchise designation is available below $10 and one at $10 or above; resulting salary determines the required term.", "Transition tags retain a player for one final year using the prior-season salary basis: under-$10 contracts double, while $10-and-over contracts add $10. The displayed current-season salary is not doubled again.", "Rookie and one waiver matching right are handled through the CVC rights workflow and final-bid match decision."] },
  { title: "Rookie Draft", content: "The rookie event precedes the regular auction. Rookie picks may be bid up to $15, and the original pick owner receives the documented final matching right." },
  { title: "Transactions & Trades", content: "FAAB claims, trade proposals, approvals, awards, cuts, and commissioner resolutions are written to the CVC transaction and audit history." },
  { title: "Playoffs & Tiebreakers", content: "Division ties use head-to-head, division record, and points scored. Cross-division ties use head-to-head and total points where required; draft order applies the related documented tiebreak logic." },
];

function value(rule: { value: unknown }) { const n = Number(rule.value); return Number.isFinite(n) ? (Number.isInteger(n) ? String(n) : n.toFixed(2)) : String(rule.value); }

export function CvcRules() {
  const rules = trpc.league.scoringRules.useQuery();
  const groups = (rules.data ?? []).reduce<Record<string, typeof rules.data>>((acc, rule) => { const key = rule.category || "Scoring"; (acc[key] ??= []).push(rule); return acc; }, {});
  return <section className="min-h-screen bg-[#06121b] px-3 pb-14 pt-6 text-white sm:px-6"><div className="mx-auto max-w-4xl"><div className="mb-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-cvc-accent">Official rulebook</p><h1 className="mt-2 font-display text-5xl uppercase">League Rules</h1><p className="mt-2 text-sm text-slate-300">CVC Fantasy Football · Approved 2026 scoring, roster, protection, auction, and transaction policies</p></div><div className="space-y-4">{policies.slice(0, 2).map((policy, index) => <RuleCard key={policy.title} icon={index === 0 ? Trophy : ShieldCheck} title={policy.title} content={policy.content} items={policy.items}/>) }<section className="overflow-hidden rounded-2xl border border-white/10 bg-white text-cvc-deep"><div className="h-1.5 bg-cvc-accent"/><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><BookOpenCheck className="text-cvc-accent"/><div><h2 className="font-display text-2xl uppercase">Scoring System</h2><p className="text-xs text-slate-500">Persisted CVC scoring rules used by Tank01 live scoring</p></div></div>{rules.isLoading ? <p className="p-5 text-sm text-slate-500">Loading CVC scoring rules…</p> : rules.error ? <p className="p-5 text-sm text-red-700">CVC scoring rules could not load.</p> : Object.entries(groups).map(([category, categoryRules]) => <div key={category} className="border-t border-slate-100 px-5 py-4"><h3 className="text-sm font-black uppercase tracking-[0.1em] text-[#244d34]">{category}</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{categoryRules?.map(rule => <li key={`${rule.category}-${rule.stat_key}`} className="rounded-lg bg-[#f0f6f1] px-3 py-2 text-sm"><span className="font-bold">{rule.label}</span><span className="float-right font-black text-cvc-accent">{value(rule)}</span>{rule.applies_to_positions?.length ? <span className="block pt-1 text-xs text-slate-500">{rule.applies_to_positions.join(" · ")}</span> : null}</li>)}</ul></div>)}</section>{policies.slice(2).map(policy => <RuleCard key={policy.title} icon={policy.title === "Auction Room" ? Gavel : ShieldCheck} title={policy.title} content={policy.content} items={policy.items}/>)}</div></div></section>;
}

function RuleCard({ icon: Icon, title, content, items }: { icon: typeof BookOpenCheck; title: string; content?: string; items?: string[] }) { return <section className="overflow-hidden rounded-2xl border border-white/10 bg-white text-cvc-deep"><div className="h-1.5 bg-cvc-accent"/><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><Icon className="text-cvc-accent"/><h2 className="font-display text-2xl uppercase">{title}</h2></div><div className="p-5 text-sm leading-7 text-slate-700">{content ? <p>{content}</p> : null}{items ? <ul className="list-disc space-y-1 pl-5">{items.map(item => <li key={item}>{item}</li>)}</ul> : null}</div></section>;
}
