import { Award, Trophy } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function CvcWrcDraftRecap() {
  const board = trpc.league.draftBoard.useQuery();
  const picks = (board.data?.picks ?? []).filter(pick => pick.currentFranchise !== "Unknown" && !/placeholder|lottery/i.test(pick.notes ?? ""));
  const recorded = picks.filter(pick => pick.pick_status !== "open");
  if (board.isLoading) return <section className="mx-auto max-w-5xl pb-10"><div className="rounded-xl border border-white/10 bg-white/5 p-7 text-center text-sm text-white/70">Loading CVC Draft Recap…</div></section>;
  return <section className="mx-auto max-w-5xl pb-10"><header className="px-1 pt-2"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#e2b23d]">Rookie draft archive</p><h1 className="mt-2 font-display text-5xl uppercase text-white">Draft Recap</h1><p className="mt-2 text-sm text-white/70">CVC rookie-draft selections and pick ownership, published as entries are recorded.</p></header>{!picks.length ? <EmptyRecap/> : <><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Configured picks" value={String(picks.length)} icon={<Award size={18}/>}/><Metric label="Selections recorded" value={String(recorded.length)} icon={<Trophy size={18}/>}/><Metric label="Draft status" value={board.data?.status?.replaceAll("_", " ") ?? "setup"} icon={<Award size={18}/>}/></div><section className="mt-6 overflow-hidden rounded-xl border border-white/10 bg-white text-cvc-deep shadow-[0_8px_24px_rgba(0,0,0,0.16)]"><div className="h-1 bg-[#e2b23d]"/><header className="bg-[#123040] px-5 py-3 font-display text-xl uppercase tracking-[0.08em] text-white">CVC Draft Board</header><div className="overflow-x-auto"><table className="min-w-[660px] w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-black uppercase tracking-[0.08em] text-slate-500"><tr><th className="px-5 py-3">Pick</th><th className="px-5 py-3">Franchise</th><th className="px-5 py-3">Selection status</th><th className="px-5 py-3">CVC note</th></tr></thead><tbody>{picks.map(pick => <tr className="border-b border-slate-100 last:border-0" key={pick.id}><td className="px-5 py-4"><span className="rounded bg-[#edf5e7] px-2 py-1 font-display text-sm text-cvc-deep">R{pick.round_number}.{String(pick.pick_number).padStart(2, "0")}</span></td><td className="px-5 py-4 font-semibold">{pick.currentFranchise}</td><td className="px-5 py-4"><span className={pick.pick_status === "open" ? "font-semibold text-slate-400" : "font-semibold text-emerald-700"}>{pick.pick_status === "open" ? "Awaiting selection" : "Selection recorded"}</span></td><td className="px-5 py-4 text-slate-500">{pick.notes ?? (pick.is_protected ? "Protected CVC pick" : "CVC rookie-draft pick")}</td></tr>)}</tbody></table></div></section><p className="mt-4 text-center text-xs text-white/50">Player-by-player recap details will appear only after CVC rookie selections are officially recorded.</p></>}</section>;
}

function EmptyRecap() { return <section className="mt-6 overflow-hidden rounded-xl border border-white/10 bg-white text-center text-cvc-deep shadow-[0_8px_24px_rgba(0,0,0,0.16)]"><div className="h-1 bg-[#e2b23d]"/><div className="px-7 py-12"><Trophy className="mx-auto text-[#dcae37]" size={48}/><h2 className="mt-4 font-display text-3xl uppercase">Draft Recap Not Yet Available</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-500">CVC rookie-draft picks have not been configured or recorded. This recap will remain empty until commissioner-approved selections exist.</p></div></section>; }
function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <section className="rounded-xl border border-white/10 bg-white px-5 py-4 text-cvc-deep shadow-[0_8px_24px_rgba(0,0,0,0.12)]"><div className="flex items-center gap-2 text-[#b9821c]">{icon}<span className="text-xs font-black uppercase tracking-[0.1em]">{label}</span></div><p className="mt-2 font-display text-3xl uppercase">{value}</p></section>; }
