// @ts-nocheck
import { trpc } from "@/lib/trpc";
import { useCvcOwnerAuth } from "@/hooks/useCvcOwnerAuth";
import { Link } from "wouter";
import { ArrowDownUp, Clock3, DollarSign, Search, ShieldCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";

const positions = ["ALL", "QB", "RB", "WR", "TE", "K", "DST"];
const badgeTone: Record<string, string> = { QB: "bg-violet-50 text-violet-700", RB: "bg-emerald-50 text-emerald-700", WR: "bg-sky-50 text-sky-700", TE: "bg-amber-50 text-amber-700", K: "bg-fuchsia-50 text-fuchsia-700", DST: "bg-slate-100 text-slate-700" };

export function CvcWrcFreeAgents() {
  const { owner } = useCvcOwnerAuth(); const utils = trpc.useUtils();
  const [position, setPosition] = useState("ALL"); const [search, setSearch] = useState(""); const [sort, setSort] = useState<"name" | "position" | "team">("name"); const [direction, setDirection] = useState<"asc" | "desc">("asc"); const [selectedPlayerId, setSelectedPlayerId] = useState(""); const [amount, setAmount] = useState("0"); const [matchingRightsOnly, setMatchingRightsOnly] = useState(false);
  const freeAgentInput = useMemo(() => ({ search: search.trim() || undefined, position: position === "ALL" ? undefined : position, limit: 100, matchingRightsOnly: matchingRightsOnly || undefined }), [position, search, matchingRightsOnly]);
  const pool = trpc.league.freeAgents.useQuery(freeAgentInput); const waiver = trpc.league.waiverStatus.useQuery(); const myBids = trpc.league.myFaabBids.useQuery(undefined, { enabled: Boolean(owner?.franchise) }); const queue = trpc.league.waiverBidQueue.useQuery(undefined, { enabled: ["commissioner", "administrator"].includes(owner?.role ?? "") });
  const submit = trpc.league.submitFaabBid.useMutation({ onSuccess: async () => { setSelectedPlayerId(""); setAmount("0"); await Promise.all([utils.league.myFaabBids.invalidate(), utils.league.activity.invalidate()]); } }); const resolve = trpc.league.resolveFaabBid.useMutation({ onSuccess: () => { utils.league.waiverBidQueue.invalidate(); utils.league.freeAgents.invalidate(); utils.league.activity.invalidate(); } });
  const players = [...(pool.data ?? [])].sort((a, b) => { const va = sort === "name" ? a.display_name : sort === "position" ? a.position ?? "" : a.nfl_team ?? ""; const vb = sort === "name" ? b.display_name : sort === "position" ? b.position ?? "" : b.nfl_team ?? ""; return String(va).localeCompare(String(vb)) * (direction === "asc" ? 1 : -1); });
  const toggleSort = (next: typeof sort) => { if (next === sort) setDirection(current => current === "asc" ? "desc" : "asc"); else { setSort(next); setDirection("asc"); } };
  const commissioner = ["commissioner", "administrator"].includes(owner?.role ?? "");
  return <div className="mx-auto max-w-[1440px]"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="cvc-eyebrow"><Users size={14} /> Player pool</div><h1 className="mt-2 font-display text-5xl uppercase leading-none tracking-[0.04em] text-white sm:text-6xl">Free Agents & FAAB</h1><p className="mt-3 max-w-3xl text-sm text-cvc-muted">Search the synchronized CVC player pool, review player availability, and submit a protected FAAB claim when the waiver window is open.</p></div><div className="rounded-lg border border-cvc-accent/35 bg-cvc-accent/10 px-4 py-3"><p className="font-display text-[11px] uppercase tracking-[.1em] text-cvc-accent">Waiver window</p><p className="mt-1 text-sm text-white">{waiver.data?.period ? `${waiver.data.period.label} open` : "No active period"}</p></div></div>
    <div className="mb-5 flex gap-1 overflow-x-auto border-b border-white/15"><button className="border-b-[3px] border-cvc-accent px-4 py-3 font-display text-sm uppercase tracking-[.08em] text-cvc-accent">Player pool</button>{owner?.franchise ? <button className="border-b-[3px] border-transparent px-4 py-3 font-display text-sm uppercase tracking-[.08em] text-white/60 hover:text-white">My claims ({myBids.data?.length ?? 0})</button> : null}{commissioner ? <button className="border-b-[3px] border-transparent px-4 py-3 font-display text-sm uppercase tracking-[.08em] text-white/60 hover:text-white">Commissioner queue ({queue.data?.length ?? 0})</button> : null}</div>
    <section className="overflow-hidden rounded-xl bg-white shadow-xl"><div className="h-1.5 bg-cvc-accent" /><div className="flex flex-wrap items-center justify-between gap-3 bg-cvc-deep px-5 py-4 text-white"><div><p className="font-display text-2xl uppercase tracking-[.06em]">Available players</p><p className="mt-1 text-xs text-white/65">Unrostered CVC player records only. Rookies remain in the rookie draft pool.</p></div><span className="text-xs font-bold uppercase tracking-[.1em] text-cvc-accent">{players.length} shown</span></div><div className="border-b border-slate-200 bg-[#edf4ee] px-4 pt-3"><div className="flex w-max min-w-full gap-1">{positions.map(item => <button key={item} onClick={() => setPosition(item)} className={position === item ? "rounded-t-md bg-cvc-deep px-3 py-2 font-display text-sm uppercase text-white" : "rounded-t-md px-3 py-2 font-display text-sm uppercase text-cvc-deep/60 hover:bg-white"}>{item}</button>)}</div></div><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search player name" className="w-full rounded-md border border-slate-200 py-2.5 pl-9 pr-3 text-sm text-cvc-deep" /></label><div className="flex flex-wrap gap-2"><button onClick={() => toggleSort("name")} className="cvc-mini-button"><ArrowDownUp size={13} /> Name</button><button onClick={() => toggleSort("position")} className="cvc-mini-button">Pos</button><button onClick={() => toggleSort("team")} className="cvc-mini-button">NFL</button><button onClick={() => setMatchingRightsOnly(current => !current)} className={matchingRightsOnly ? "cvc-mini-button bg-cvc-deep text-white" : "cvc-mini-button"}><ShieldCheck size={13} /> Matching rights only</button></div></div>
      <div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left"><thead className="bg-[#edf4ee]"><tr className="font-display text-xs uppercase tracking-[.08em] text-cvc-deep"><th className="px-5 py-4">Player</th><th className="px-3 py-4">Position</th><th className="px-3 py-4">NFL team</th><th className="px-3 py-4">Availability</th><th className="px-5 py-4 text-right">FAAB</th></tr></thead><tbody>{pool.isLoading ? <tr><td colSpan={5} className="px-5 py-8 text-center text-sm text-slate-500">Loading CVC player pool…</td></tr> : pool.error ? <tr><td colSpan={5} className="px-5 py-8 text-center text-sm text-red-700">{pool.error.message}</td></tr> : players.length ? players.map(player => <tr key={player.id} className="border-t border-slate-200 hover:bg-slate-50"><td className="px-5 py-3"><Link href={`/player/${player.id}`} className="font-semibold text-cvc-deep hover:text-cvc-accent">{player.display_name}</Link>{player.cutByFranchiseName ? <p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.06em] text-amber-600">Matching rights: {player.cutByFranchiseName}</p> : null}</td><td className="px-3 py-3"><span className={`rounded px-2 py-1 text-[10px] font-bold uppercase tracking-[.08em] ${badgeTone[player.position] ?? "bg-slate-100 text-slate-700"}`}>{player.position ?? "—"}</span></td><td className="px-3 py-3 text-sm text-slate-600">{player.nfl_team ?? "FA"}</td><td className="px-3 py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-emerald-700">Available</span></td><td className="px-5 py-3 text-right">{owner?.franchise && waiver.data?.period ? <button onClick={() => setSelectedPlayerId(player.id)} className="cvc-mini-button"><DollarSign size={13} /> Bid</button> : <span className="text-xs text-slate-400">{owner ? "Window closed" : "Sign in"}</span>}</td></tr>) : <tr><td colSpan={5} className="px-5 py-8 text-center text-sm text-slate-500">{matchingRightsOnly ? "No free agents currently carry a matching-rights tag." : "No available players match this filter."}</td></tr>}</tbody></table></div></section>
    {selectedPlayerId ? <section className="mt-6 rounded-xl border border-cvc-accent/40 bg-cvc-accent/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-xl uppercase text-white">Submit FAAB claim</p><p className="mt-1 text-sm text-cvc-muted">Bid on the selected player. CVC records the claim for commissioner resolution.</p></div><button onClick={() => setSelectedPlayerId("")} className="text-xs font-bold uppercase tracking-[.08em] text-cvc-muted">Cancel</button></div><div className="mt-4 flex flex-wrap gap-3"><input value={amount} onChange={event => setAmount(event.target.value.replace(/\D/g, ""))} className="w-36 rounded-md border border-white/20 bg-cvc-deep px-3 py-2 text-sm text-white" inputMode="numeric" placeholder="$0" /><button disabled={submit.isPending || Number(amount) < 0} onClick={() => submit.mutate({ playerId: selectedPlayerId, amount: Number(amount) })} className="cvc-button-compact disabled:opacity-50">{submit.isPending ? "Submitting…" : "Submit claim"}</button>{submit.error ? <p className="self-center text-sm text-red-200">{submit.error.message}</p> : null}</div></section> : null}
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-white/10 bg-cvc-deep/60 p-5"><div className="flex items-center gap-2 text-cvc-accent"><Clock3 size={16} /><p className="font-display text-lg uppercase">My claim status</p></div><div className="mt-4 space-y-2">{owner?.franchise ? myBids.data?.length ? myBids.data.map((bid: any) => <div key={bid.id} className="rounded bg-white/5 px-3 py-2 text-sm text-white"><b>{bid.player?.[0]?.display_name}</b> · ${bid.amount} · <span className="uppercase text-cvc-accent">{bid.status}</span></div>) : <p className="text-sm text-cvc-muted">No CVC waiver claims submitted.</p> : <p className="text-sm text-cvc-muted">Sign in with an owner account to submit and review claims.</p>}</div></section><section className="rounded-xl border border-white/10 bg-cvc-deep/60 p-5"><div className="flex items-center gap-2 text-cvc-accent"><ShieldCheck size={16} /><p className="font-display text-lg uppercase">Commissioner queue</p></div><div className="mt-4 space-y-2">{commissioner ? queue.data?.length ? queue.data.map((bid: any) => <div key={bid.id} className="flex flex-wrap items-center justify-between gap-2 rounded bg-white/5 px-3 py-2 text-sm text-white"><span><b>{bid.player?.[0]?.display_name}</b> · {bid.franchise?.[0]?.name} · ${bid.amount}</span><span className="flex gap-2"><button onClick={() => resolve.mutate({ bidId: bid.id, outcome: "won" })} className="cvc-mini-button">Award</button><button onClick={() => resolve.mutate({ bidId: bid.id, outcome: "lost" })} className="cvc-mini-button">Lost</button></span></div>) : <p className="text-sm text-cvc-muted">No pending CVC waiver claims.</p> : <p className="text-sm text-cvc-muted">Protected commissioner controls appear for commissioner and administrator accounts.</p>}</div></section></div>
  </div>;
}
